version: "3.6"
services:
  api:
    image: ghcr.io/perceptimatic/sfo-api:latest
    build:
      context: ./api
      args:
        UPLOAD_DIR: $UPLOAD_DIR
    ports:
      - ${APP_PORT}:80
    environment:
      - API_HOST_PORT
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - JWT_SECRET
      - FAST_API_DEFAULT_ADMIN_PASSWORD
      - UPLOAD_DIR
      - POSTGRES_DB
      - POSTGRES_HOST_AUTH_METHOD
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - PROCESSING_QUEUE
      - STORAGE_DRIVER
    volumes:
      - ./uploads:${UPLOAD_DIR}
      - ./api:/code
    networks:
      - speech-feature
  worker:
    image: ghcr.io/perceptimatic/sfo-worker:latest
    depends_on:
      - postgres
      - redis
    build:
      context: ./worker
      args:
        UPLOAD_DIR: $UPLOAD_DIR
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_DEFAULT_REGION
      - AWS_SECRET_ACCESS_KEY
      - BUCKET_NAME
      - POSTGRES_DB
      - POSTGRES_HOST_AUTH_METHOD
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - PROCESSING_QUEUE
      - SENDER_EMAIL
      - SMTP_SERVER
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_LOGIN
      - SMTP_PASSWORD
      - STATIC_ASSET_URL
      - STORAGE_DRIVER
      - UPLOAD_DIR
    entrypoint: [ "celery", "-A", "app.worker", "worker", "-E", "-l", "debug", "-Q", "${PROCESSING_QUEUE}" ]
    volumes:
      - ./uploads:${UPLOAD_DIR}
      - ./worker:/code
      - ./api/static:/srv/results
    networks:
      - speech-feature
  react:
    image: node:latest
    volumes:
      - ./react:/usr/app
    environment:
      - API_HOST_PORT
      - AWS_DEFAULT_REGION
      - REACT_PORT
      - REACT_TMP_CRED_ENDPOINT
      - REACT_UPLOAD_ENDPOINT
      - STORAGE_DRIVER
      - BUCKET_NAME
    working_dir: /usr/app
    networks:
      - speech-feature
    entrypoint: "yarn start"
    ports:
      - ${REACT_PORT}:${REACT_PORT}
  redis:
    image: redis:latest
    networks:
      - speech-feature
  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - worker
      - postgres
      - redis
    ports:
      - 5555:5555
    networks:
      - speech-feature
  postgres:
    image: postgres:latest
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_HOST_AUTH_METHOD
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_ROOT_PASSWORD
    user: ${UIDGID:-root:root}
    networks:
      - speech-feature
networks:
  speech-feature: